### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ylxb2016** [rndusr/torf-cli#11]
Thank you! This tool is too powerful, but there is a small regret that it is impossible to view and modify the "source" field of the private torrent file. Can you add this feature? Because the "source" field is important for private trackers.
Ps: You can view and modify the ‘’source’’ field of the torrent file via https://github.com/drizt/torrent-file-editor this, but this tool cannot be operated by commander.

**Comment by rndusr** [comment]
It's on my todo list, there's just so much stuff to do.

It should be relatively simple to add since all the functionality is implemented
for other fields, e.g. 'comment', and the Torrent class already supports
'source'. Just in case you (or anyone else) wants to take a stab at this.

**Comment by ylxb2016** [comment]
> It's on my todo list, there's just so much stuff to do. It should be relatively simple to add since all the functionality is implemented for other fields, e.g. 'comment', and the Torrent class already supports 'source'. Just in case you (or anyone else) wants to take a stab at this.

thanks! I wait for this powerful feature for a long time.

**Comment by rndusr** [comment]
I added the --source and --nosource options.
