### ISSUE TITLE
Command line option to force formatted output even when piping stdout

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/torf-cli#2]
It would be useful to have a command-line option to force a formatted output even when piping the output.

Here's why: I'm replacing `transmission-show` with `dorf` to show torrent files attached to mail messages and also on `mc`. In both cases, the output is piped to an internal pager, so the result is, for instance, with `mc`:
![image](https://user-images.githubusercontent.com/10074769/40276125-0feba802-5bd8-11e8-95de-42689a35ad49.png)
It's perfect for parsing, I can see there's a single TAB character between each header and its value, but not for viewing. `mc` pipes the output to its interval viewer. With `neomutt`, of course, the result will be the same, since it also pipes the output to its internal viewer:
![image](https://user-images.githubusercontent.com/10074769/40276144-95b2e6da-5bd8-11e8-85a2-77f15c44d916.png)

An explicit option to force formatted output would be ideal for these cases.

**Comment by rndusr** [comment]
I completely agree.

**Comment by rndusr** [comment]
This is fixed in master by the introduction of `--human` and `--nohuman`.

Thanks for your support.

**Comment by rndusr** [comment]
Thanks a lot! I'm glad you find it useful.
