### ISSUE TITLE
Differentiate adding trackers via CSV and -t

### ISSUE THREAD

**Issue by vRobM** [rndusr/torf-cli#22]
When adding trackers to a .torrent via -t t1,t2,t3, it adds them all under one block.
When adding trackers to a .torrent via -t t1 -t t2 -t t3, it does the same.

Adding via separate -t parameters, it should add that -t set + and CSV into one block, and the next -t into a new block.

some torrent clients only use the first tracker in a block.
separating each tracker into separate blocks uses all trackers at once.

**Comment by rndusr** [comment]
Works for me:

    $ torf foo -t http://foo:123,http://foo:456 -t http://bar:789
    [...]
       Trackers  Tier 1: http://foo:123
                         http://foo:456
                 Tier 2: http://bar:789

What does `torf --version` say?

**Comment by vRobM** [comment]
3.2.0

There appears to be intermittent behavior and tracker printing problems.

After just adding 5 trackers, the output does not show tiers from the command adding them or separately, after the fact. Loading up the torrent though does show separate trackers rather than a list.

hope that helps reproduce it.

**Comment by rndusr** [comment]
Can you give me an exact command?

**Comment by vRobM** [comment]
torf -i a.torrent -t http://foo:1 -t http://foo:2 -t http://foo:3 -t http://foo:4 -t http://foo:5 -o b.torrent

Trackers  http://foo:1
              http://foo:2
              http://foo:3
              http://foo:4
              http://foo:5

**Comment by rndusr** [comment]
OK, I can reproduce it. It seems to happen if there is only one tracker in a tier.

Thanks.

**Comment by vRobM** [comment]
Thank you, for taking a serious look.

**Comment by rndusr** [comment]
OK, turns out this isn't really a bug, it's just bad UX.

The trackers are stored in multiple tiers as expected, but torf doesn't display
different tiers if all tiers contain only one tracker. That's why it looks like
they are all in the same tier.

I'm not sure what the best fix would be. If there is only one tracker, it looks
weird with "Tier 1:" in front of the URL. I guess the best solution would be to
always display the tiers unless there is only a single tracker in a single tier.

I'm open for suggestions.

**Comment by vRobM** [comment]
Being explicit makes sense.
Perhaps add another label for the non-tier structure. List perhaps.

**Comment by vRobM** [comment]
Another input method would also be interesting, such as an interactive mode, where one can pick a section to edit, then get a free form text box to paste a bunch of information, and after it's parsed torf asks the intent, list of tier mode, taking any indents and spaces into consideration, etc.

I realize that's a big feature, but also a more human friendly approach.

**Comment by rndusr** [comment]
You mean torf should list the trackers twice, once as a flat list and then again as tiers?

That just adds clutter in my opinion. Especially for single-tracker torrents.

**Comment by rndusr** [comment]
Yeah, that's a very big feature.

Maybe an option to edit the tracker list in $EDITOR would be nice. But that wouldn't solve the display issue.

**Comment by vRobM** [comment]
> 
> You mean torf should list the trackers twice, once as a flat list and then again as tiers? That just adds clutter in my opinion. Especially for single-tracker torrents.

no, only one at a time, but distinguish. So either it's a tiered list or a list of tiers, but it should be obvious in the representation.

**Comment by rndusr** [comment]
How would torf decide which display style to use?

**Comment by vRobM** [comment]
start with the Tier. 

By default the 0 Tier is always present and either has a list of trackers or only one.
rinse repeat for additional tiers.

**Comment by rndusr** [comment]
I went with my original idea of always showing the tier unless there only a
single tracker, which is the only case where tiers are really irrelevant.
