### ISSUE TITLE
Feature Request : Remove files from .torrent

### ISSUE THREAD

**Issue by swannie-eire** [rndusr/torf-cli#23]
It would be a beneficial feature to be able to remove files from a torrent file as it would mean we do not have to create a new torrent.

Use Case:
You have a torrent that contains a large video file and some small text files. 
You want to upload the torrent on another site but do not want to include the small test files only the video file.
Currently we would have to recreate the torrent with just the large video file and this can be time consuming. 
As we already have the large file pieces in the exisiting torrent it would be great if we could remove the small files from the exsiting torrent.

This tool appears to have this feature - https://torrent-file-editor.github.io/

**Comment by rndusr** [comment]
Removing files changes the "info" field. The torrent hash is created from the
"info" field. Therefore, you can't remove files from a torrent without
re-hashing (i.e. creating a new torrent).

What you want to do should be possible with the --exclude option:

    torf -i original.torrent path/to/content --exclude '*.txt' -o new.torrent

However, any operation that changes the hash means you need to have the files.
