### ISSUE TITLE
PackageNotFoundError

### ISSUE THREAD

**Issue by Soundtoxin** [rndusr/torf-cli#24]
```
Traceback (most recent call last):
  File "/usr/bin/torf", line 33, in <module>
    sys.exit(load_entry_point('torf-cli==3.2.0', 'console_scripts', 'torf')())
  File "/usr/bin/torf", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: torf-cli
```

Running Arch and using the torf-cli AUR package.

**Comment by rndusr** [comment]
I don't maintain the AUR package.

Please report this to the package maintainer.
https://aur.archlinux.org/packages/torf-cli/

**Comment by Soundtoxin** [comment]
Yeah? That feels like a pretty minor detail to me. So is there no bug in the software to be addressed here or anything? I wonder what you would've said had I omitted the AUR detail. I reported the problem on the AUR page as well, but since it's just grabbing the files from here I can't imagine there's much to be done on their end unless dependencies changed recently or something.

**Comment by rndusr** [comment]
I just re-installed with `pipx install torf-cli` and everything works as
expected. If that doesn't work for you, I'll be happy to look into it, but I
can't fix a package I'm not maintaining for a distro I'm not familiar with.

**Comment by Soundtoxin** [comment]
Thanks! The pipx version does indeed seem to work. Sorry for the trouble.
