### ISSUE TITLE
Feature Request: Control number of hashing threads

### ISSUE THREAD

**Issue by fbdtemme** [rndusr/torf-cli#25]
Could it be possible to add an option like --threads or --workers to control the number of hashing threads?
As part of my own tool I am creating a [benchmark](https://github.com/fbdtemme/torrenttools#performance) of multiple bittorrent metafile utilities.
I want to include this tool but I need to control the number of hashing threads for a fair comparison.

**Comment by rndusr** [comment]
Thanks for reminding me. I made a new release that adds the --threads option.

torrenttools looks like a really cool project!
