### ISSUE TITLE
Windows 10: How to edit source and create new torrent in Batch Mode?

### ISSUE THREAD

**Issue by kdantas** [rndusr/torf-cli#27]
Hi, I have a folder with 50 .torrent files. How can I run torf-cli to change the annouce and the source of these 50 .torrent files in batch mode? And, is there any way to run torf-cli in Windows terminal? Thanks in advance. 

PS: I installed pipx in my window and then I installed torf. But I got this error below when run torf. Any idea how to solve this problem?

`C:\>torf -i Mirc.torrent
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\torf.exe\__main__.py", line 7, in <module>
  File "C:\Users\xandynho\AppData\Roaming\Python\Python38\site-packages\torfcli\__init__.py", line 16, in run
    from . import _config, _errors, _main, _ui
  File "C:\Users\xandynho\AppData\Roaming\Python\Python38\site-packages\torfcli\_ui.py", line 24, in <module>
    from . import _term, _utils, _vars
  File "C:\Users\xandynho\AppData\Roaming\Python\Python38\site-packages\torfcli\_term.py", line 14, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'`

**Comment by rndusr** [comment]
I don't know what "batch mode" means, but I don't think torf-cli has one. I
would do it with a for loop. How to do it specifically depends on your shell,
the files and what you want to do.

No idea how to get torf-cli working on Windows, especially if you don't provide
any error messages.

**Comment by kdantas** [comment]
> 
> I don't know what "batch mode" means, but I don't think torf-cli has one. I would do it with a for loop. How to do it specifically depends on your shell, the files and what you want to do. No idea how to get torf-cli working on Windows, especially if you don't provide any error messages.

Hi @rndusr, thanks for your reply. Batch reply means, in general, what you wrote, run it with a for loop. And about the error message running in windows, you can check in my main post. But see below again...

C:\>torf -i Mirc.torrent

**Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\torf.exe\__main__.py", line 7, in <module>
  File "C:\Users\xandynho\AppData\Roaming\Python\Python38\site-packages\torfcli\__init__.py", line 16, in run
    from . import _config, _errors, _main, _ui
  File "C:\Users\xandynho\AppData\Roaming\Python\Python38\site-packages\torfcli\_ui.py", line 24, in <module>
    from . import _term, _utils, _vars
  File "C:\Users\xandynho\AppData\Roaming\Python\Python38\site-packages\torfcli\_term.py", line 14, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'**

But I think the problem must be about this last line... **ModuleNotFoundError: No module named 'termios'**. I read that this termios module can´t be installed on Windows. Anyway, I'll keep looking for a solution to run TORF on windows.

**Comment by rndusr** [comment]
Thanks for providing an error. (I don't get another email if you edit a comment,
that's why I didn't see it.)

I think I can fix this particular issue, but I can't test it, so expect more
bugs.

**Comment by rndusr** [comment]
The ModuleNotFoundError should be fixed.

**Comment by kdantas** [comment]
> 
> Thanks for providing an error. (I don't get another email if you edit a comment, that's why I didn't see it.) I think I can fix this particular issue, but I can't test it, so expect more bugs.

Hey @rndusr, do you really can fix this problem? Maybe creating a patch. I can test here and give you a feedback. Please, let me know. I would like to run TORF on windows. Regards.

**Comment by rndusr** [comment]
I think I have fixed the ModuleNotFoundError.

Please install/clone the master branch on GitHub and report if it works or if
you get a different error message.

**Comment by kdantas** [comment]
> 
> You're not using master. The traceback you're posting complains about line 14 in _term.py, which is "import termios", but that's not what that line says in master: https://github.com/rndusr/torf-cli/blob/master/torfcli/_term.py#L14

I am doing something wrong? Is this link (https://github.com/rndusr/torf-cli/archive/refs/heads/master.zip) correct or not for master?  Any suggest? My knowledgement in linux and terminal commands is not so good, but I am trying to do my best.

**Comment by kdantas** [comment]
See the contents of my _term.py:

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details
# http://www.gnu.org/licenses/gpl-3.0.txt

import io
import sys
import termios
import tty

# References:
#   https://www.vt100.net/docs/vt100-ug/chapter3.html#DECSCNM
#   http://ascii-table.com/ansi-escape-sequences.php
#   http://ascii-table.com/ansi-escape-sequences-vt-100.php

erase_line         = '\x1b[2K'
erase_to_eol       = '\x1b[K'
reverse_on         = '\x1b[7m'
reverse_off        = '\x1b[0m'
hide_cursor        = '\x1b[?25l'
show_cursor        = '\x1b[?25h'
ensure_line_below  = '\n\x1b[1A'
save_cursor_pos    = '\x1b7'
restore_cursor_pos = '\x1b8'
move_pos1          = '\r'
move_up            = '\x1b[1A'
move_down          = '\x1b[1B'
move_right         = '\x1b[1C'
move_left          = '\x1b[1D'

def echo(*names):
    seqs = ''.join(globals()[name] for name in names)
    print(seqs, end='')

def getch():
    with raw_mode:
        return sys.stdin.read(1)

class _raw_mode():
    _orig_attrs = None

    def enable(self):
        try:
            fd = sys.stdin.fileno()
            self._orig_attrs = termios.tcgetattr(fd)
            tty.setraw(sys.stdin.fileno())
        except io.UnsupportedOperation:
            pass

    def disable(self):
        try:
            if self._orig_attrs is not None:
                fd = sys.stdin.fileno()
                termios.tcsetattr(fd, termios.TCSADRAIN, self._orig_attrs)
        except io.UnsupportedOperation:
            pass

    def __enter__(self):
        self.enable()

    def __exit__(self, _, __, ___):
        self.disable()

raw_mode = _raw_mode()

class _no_user_input():
    """Disable printing of characters as they are typed and hide cursor"""
    def enable(self):
        try:
            fd = sys.stdin.fileno()
            self._orig_attrs = termios.tcgetattr(fd)
            new = termios.tcgetattr(fd)
            new[3] = new[3] & ~termios.ECHO  # lflags
            termios.tcsetattr(fd, termios.TCSADRAIN, new)
            echo('hide_cursor')
        except io.UnsupportedOperation:
            pass

    def disable(self):
        orig_attrs = getattr(self, '_orig_attrs', None)
        if orig_attrs is not None:
            try:
                fd = sys.stdin.fileno()
                termios.tcsetattr(fd, termios.TCSADRAIN, orig_attrs)
                echo('show_cursor')
            except io.UnsupportedOperation:
                pass

    def __enter__(self):
        self.enable()

    def __exit__(self, _, __, ___):
        self.disable()

no_user_input = _no_user_input()

**Comment by kdantas** [comment]
See the conent of my _term.py file

[https://pastebin.com/10yahi7j](url)

**Comment by rndusr** [comment]
I don't know why installing master with pipx didn't work for you. I would've
used this command:

    pipx install 'git+git://github.com/plotski/upsies.git'

The strange characters are control characters for cursor movement, clearing the
current line, etc. They are usually supported on Unix terminals, but your
terminal doesn't seem to understand them.

It's not hard to fix this in principle, but I don't know anything about the
terminal you're using. I would need to know how to detect it and the control
characters it supports.

**Comment by kdantas** [comment]
Hi @rndusr, I'm sharing a file (LinesEnd.txt) where I saved the strange characters on windows. When you have time, see if you can fix this problem. Thank you very much. 

http://www.fileconvoy.com/dfl.php?id=g6398d39df890191a1000384114599c25c687db68b0

Looking on google, I found some articles that shows how to check what these strange characters represent. Perhaps these information can help you find the solution. These tests were done on Windows WSL running Ubuntu 18.04.4 LTS. Best Regards.

kdantas@LAPTOP-J2M6QHEU:/mnt/c/users/xandynho/desktop$ **cat -e LinesEnd.txt**
Name  Mirc.torrent^[[K^M$
  Info Hash  f8ebd04c5e10ee5c32564c6ca6b8ec342f3c2016^[[K^M$
       Size  3.35 KiB^[[K^M$
    Created  2021-10-12 22:19:20^[[K^M$
 Created By  torf 3.4.0^[[K^M$
 Piece Size  16 KiB^[[K^M$
Piece Count  1^[[K^M$
 File Count  1^[[K^M$
      Files  Mirc.torrent [3.35 KiB]^[[K^M$
     Magnet  magnet:?xt=urn:btih:f8ebd04c5e10ee5c32564c6ca6b8ec342f3c2016&dn=Mirc.torrent&xl=3431^[[K

kdantas@LAPTOP-J2M6QHEU:/mnt/c/users/xandynho/desktop$ **cat -v LinesEnd.txt**
Name  Mirc.torrent^[[K^M
  Info Hash  f8ebd04c5e10ee5c32564c6ca6b8ec342f3c2016^[[K^M
       Size  3.35 KiB^[[K^M
    Created  2021-10-12 22:19:20^[[K^M
 Created By  torf 3.4.0^[[K^M
 Piece Size  16 KiB^[[K^M
Piece Count  1^[[K^M
 File Count  1^[[K^M
      Files  Mirc.torrent [3.35 KiB]^[[K^M
     Magnet  magnet:?xt=urn:btih:f8ebd04c5e10ee5c32564c6ca6b8ec342f3c2016&dn=Mirc.torrent&xl=3431^[[K

kdantas@LAPTOP-J2M6QHEU:/mnt/c/users/xandynho/desktop$ **file LinesEnd.txt**
LinesEnd.txt: ASCII text, with CRLF line terminators, with escape sequences

kdantas@LAPTOP-J2M6QHEU:/mnt/c/users/xandynho/desktop$ **file -k LinesEnd.txt**
LinesEnd.txt: ASCII text, with CRLF line terminators, with escape sequences\012- data
