### ISSUE TITLE
Output only the magnet link when piping the output of `torf -m`

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/torf-cli#3]
When creating a magnet link (`torf -m`), it would be more useful to output only the magnet link if stdout is piped, to avoid unnecessary parsing, so that this (on bash):

```
magnet=$(torf -m foo)
```

wouldn't need any extra parsing. Of course, it's trivial to parse the output, but it feels more natural/intuitive if `torf -m` piped only the magnet link.

**Comment by rndusr** [comment]
I'm not quite convinced. I get the idea, and it makes sense. But output isn't
always piped when a magnet link is created, and it wouldn't be consistent with
the creation of torrent files.

How about another option, e.g. `--magnet-only` / `-mo`?

**Comment by marcelpaulo** [comment]
An option would fit more orthogonally with the `torf`-way and `stig`-way of doing things: formatted output on a tty and parseable output when piped, different format but same content. I completely agree.

**Comment by marcelpaulo** [comment]
Thinking a little bit more about it, I don't think this is necessary. It doesn't fit with torf's philosophy. As the output is parseable when redirected, that's more than enough.

**Comment by rndusr** [comment]
Thanks! I was thinking about this but couldn't come up with a good solution.

Making an option for the magnet link only feels incomplete. I was considering
adding options for magnet/name/size/etc, but that would add so much clutter for
functionality that is already provided by pipes.

Now I can hopefully make a new release soon.

**Comment by marcelpaulo** [comment]
I always forget about `cut`. Good idea!
