### ISSUE TITLE
Append the name of the torrent file created with the profile name.

### ISSUE THREAD

**Issue by Ravencentric** [rndusr/torf-cli#32]
For example,
If the input is: `torf -z public demo-folder`
then the resulting .torrent file should be named something like `[public] demo-folder.torrent` or `PUBLIC.demo-folder.torrent`
and if the input is: `torf -z private demo-folder`
then the resulting .torrent file should be named something like `[private] demo-folder.torrent` or `PRIVATE.demo-folder.torrent`

Basically appending the profile name at the start of the torrent file to prevent overwriting and help recognizing what `.torrent` file is made with what profile when making multiple torrents using multiple profiles for the same folder/file.

**Comment by rndusr** [comment]
Profile names are now appended to the torrent name because it sorts better in my opinion.
