### ISSUE TITLE
question: any way to reuse a torrent that gives error ['info']['piece length'] is invalid

### ISSUE THREAD

**Issue by swannie-eire** [rndusr/torf-cli#35]
i have a torrent that i wanted to reuse but change source and trackers but am getting the following error.

torf: Invalid metainfo: ['info']['piece length'] is invalid: 827392

torrent seems to add fine and download fine in qbittorrent.

question: any way to reuse a torrent that gives this error ['info']['piece length'] is invalid

**Comment by rndusr** [comment]
The piece length is not nicely divisible by 16 Kib:

    827392 / (16 * 1024) = 50.5

Try --novalidate or -V.

**Comment by swannie-eire** [comment]
Thank you. 

Weird I know. Don't know how you can even create torrent like this.

**Comment by swannie-eire** [comment]
Thank you. 

Weird I know. Don't know how you can even create torrent like this.
