### ISSUE TITLE
[Question] Is it possible to set entropy field to a random number?

### ISSUE THREAD

**Issue by swannie-eire** [rndusr/torf-cli#37]
On a tracker one of the requirements is set entropy field to a random number.

Is this possible with torf-cli?

First time i ever heard of entropy field and i cant find anything online about it with any torrent creator tool

**Comment by swannie-eire** [comment]
found it

--xseed, -x

       Randomize the info hash to help with cross-seeding. 

       This simply adds an entropy field to the info section of the metainfo 

       and sets it to a random integer.

**Comment by rndusr** [comment]
Thanks for supporting yourself. :)
