### ISSUE TITLE
Exclude hidden files by default

### ISSUE THREAD

**Issue by fashionableDark** [rndusr/torf-cli#38]
torf 5.1.0
python 3.12.2
Windows 10 Pro

Doing a simple `torf -x -p DIRECTORY` will include `Thumbs.db` in that directory, which is undesirable and unexpected. Many users have hidden files showing in Explorer, but very few have "protected operating system files" set to show. From a quick test, I observed that qBittorrent's torrent creator excludes hidden files, both "protected system files" like `Thumbs.db` and just plain hidden files.

**Comment by rndusr** [comment]
This would have to be implemented in torf, probably here:

https://github.com/rndusr/torf/blob/master/torf/_utils.py#L133

I don't have Windows so I can't do it.
