### ISSUE TITLE
Option to generate the magnet link when creating a new torrent

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/torf-cli#4]
It would be useful to generate a magnet link when creating a new torrent, I guess by default, or perhaps actioned by a command line option.

Here's the situation: I want to send someone a file, so I create a torrent, start seeding it, and would like to send the corresponding magnet link to this someone.

**Comment by rndusr** [comment]
I should've read this before commenting on #3. Now that makes more sense.

I'll think about this.

**Comment by marcelpaulo** [comment]
Hey, 9515254c2833fde2f1cbc380833de46d71f21c46 implements this. Great, thanks !

**Comment by rndusr** [comment]
Right. Thanks for keeping track.
