### ISSUE TITLE
setup.py: FileNotFoundError: torfcli/__vars__.py

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/torf-cli#7]
*torfcli/\__vars__.py* was renamed to *torfcli/_vars.py* but *setup.py* is still referencing *torfcli/\__vars__.py*:

```
paulo:~/src/torf-cli$ python3 setup.py install --user
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    with open('torfcli/__vars__.py') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'torfcli/__vars__.py'
```

Running 435d328dfb9454793704e32e2d9ecf100ccff33f.

**Comment by rndusr** [comment]
Thanks for the heads up. Should be fixed now.

**Comment by marcelpaulo** [comment]
Thanks, @rndusr ! Not sure if it was already there before this last batch of commits, but great stuff the configuration file and the profiles ! Will cut down my script using them.

**Comment by rndusr** [comment]
It was already there, but it wasn't quite complete.

And it's still not perfect. Originally, the idea was to allow arbitrary options
in the config file, both in the global options and in profiles. That would
include --config and --profile, so you could load a profile from a profile or
even load a different config file and load more profiles from there and so on.

But I couldn't get it to work correctly, and I'm not even sure there's a use
case for complex setups like that. Would you find that useful?

**Comment by rndusr** [comment]
Okay, thanks for your opinion. Looks like I'm feature creeping again.

I like your idea regarding environment variables. Feel free to open an issue on that one.

**Comment by marcelpaulo** [comment]
> feature creeping

Had never heard the expression ! And yeah, you were !
